global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"] # Node Exporter default port
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8397"]
