networks:
  frontend:
    ipam:
      config:
        - subnet: ${DOCKER_SUBNET_1:-172.20.0.0/24}
services:
  duckdns:
    image: linuxserver/duckdns
    dns: 1.1.1.1
    environment:
      - PUID=$PUID_USER
      - PGID=$PGID_USER
      - TZ=$TZ
      - SUBDOMAINS=$DUCKDNS_DOMAIN
      - TOKEN=$DUCKDNS_TOKEN
      - LOG_FILE=false
    volumes:
      - $DOCKER_CONFIG_PATH/duckdns:/config
    restart: always

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # DNS Ports
      - "53:53/tcp"
      - "53:53/udp"
      # Default HTTP Port
      - "8002:80/tcp"
      # Default HTTPs Port. FTL will generate a self-signed certificate
      - "455:443/tcp"
      # Uncomment the line below if you are using Pi-hole as your DHCP server
      # - "67:67/udp"
      # Uncomment the line below if you are using Pi-hole as your NTP server
      #- "123:123/udp"
    environment:
      # Set the appropriate timezone for your location (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones), e.g:
      TZ: $TZ
      # Set a password to access the web interface. Not setting one will result in a random password being assigned
      FTLCONF_webserver_api_password: $PIHOLE_PWD
      # If using Docker's default `bridge` network setting the dns listening mode should be set to 'all'
      FTLCONF_dns_listeningMode: "all"
      PIHOLE_DNS_: 1.1.1.1;8.8.8.8

      # FTLCONF_LOCAL_IPV4: 192.168.1.100
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - $DOCKER_CONFIG_PATH/pihole/etc/pihole/:/etc/pihole/
      - $DOCKER_CONFIG_PATH/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards. Needs environment variable FTLCONF_misc_etc_dnsmasq_d: 'true'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      # - NET_ADMIN
      # Required if you are using Pi-hole as your NTP client to be able to set the host's system time
      # - SYS_TIME
      # Optional, if Pi-hole should get some more processing time
      - SYS_NICE
    networks:
      frontend:
        ipv4_address: ${PIHOLE_DOCKER_SUB_IP_DNS:-172.20.0.100}
    restart: always

  wireguard:
    image: linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=$PUID_USER
      - PGID=$PGID_USER
      - TZ=$TZ
      - SERVERURL=${DUCKDNS_DOMAIN}.duckdns.org
      - SERVERPORT=51821 #optional
      - PEERS=$WG2_PEERS #optional
      - PEERDNS=${PIHOLE_DOCKER_SUB_IP_DNS:-172.20.0.100}
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - $DOCKER_CONFIG_PATH/wireguard/config:/config
      - /lib/modules:/lib/modules
      - /usr/src/:/usr/src
    depends_on:
      - pihole
    ports:
      - 51821:51820/udp
    networks:
      - frontend
    restart: always
