---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Beefunk"
#subtitle: "Home server"
#logo: ""
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: False # Set to false to hide the header
footer: '<p>Created with <span class="has-text-danger">❤️</span>. Click on  <a href="http://beefunk:3000/s/H1tA_LShH" target="_.local">Server How to</a> to understand how to get by.</i></a></p>' # set false if you want to hide it.header:
connectivityCheck: true
# Optional theming
#theme: default # 'default' or one of the theme available in 'src/assets/themes'.

theme: dark
colors:
  dark:
    highlight-primary: "#2b2b2b"
    highlight-secondary: "#484d54"
    highlight-hover: "#cfdfae"
    background: "#1313134a"
    card-background: "#2b2b2b"
    text: "#cadfae"
    text-header: "#cfdfae"
    text-title: "#cfdfae"
    text-subtitle: "#cfdfae"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#cfdfae"
  light:
    highlight-primary: "#2b2b2b"
    highlight-secondary: "#484d54"
    highlight-hover: "#cfdfae"
    background: "#1313134a"
    card-background: "#2b2b2b"
    text: "#cadfae"
    text-header: "#cfdfae"
    text-title: "#cfdfae"
    text-subtitle: "#cfdfae"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#cfdfae"
  # light:
  #highlight-primary: "#3367d6"
  #highlight-secondary: "#4285f4"
  #highlight-hover: "#5a95f5"
  #background: "#f5f5f5"
  #card-background: "#ffffff"
  #text: "#363636"
  #text-header: "#424242"
  #text-title: "#303030"
  #text-subtitle: "#424242"
  #card-shadow: rgba(0, 0, 0, 0.1)
  #link-hover: "#363636"

# Optional message
message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  style: "is-warning"
  title: "Welcome to Beefunk!!"
  content: '<a href="http://home.beefunk.local">http://home.beefunk.local</a> <br> Find more information about this media server at <a href="http://beefunk:3000/s/H1tA_LShH" target="_.local">Server How to</a>'
  #content: "http://beefunk"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  #  - name: "Github"
  #icon: "fab fa-github"
  #url: "https://github.com/lbesnard"
  #    target: "_.local" # optional html tag target attribute
  - name: "Server Howto"
    icon: "fas fa-book"
    #logo: "assets/alert.png"
    url: "http://beefunk:3000/s/H1tA_LShH"
    target: "_.local" # optional html tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: ""
    icon: "assets/alert.png"
    items:
      - name: "Mealie"
        logo: "https://avatars.githubusercontent.com/u/92342333?s=48&v=4"
        #subtitle: "Explains the bells and whistles of the server"
        url: "http://mealie.beefunk.local"
        target: "_.local" # optional html tag target attribute

  # - name: Nextcloud
  #   type: Nextcloud
  #   logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nextcloud.svg"
  #   url:
  #     https://nextcloud.funkbrownfunk.duckdns.org
  #
  # - name: "SearX"
  #   subtitle: "Self-hosted search engine"
  #   logo: "assets/searx.png"
  #   url: "https://searx.funkybeefunk.duckdns.org/search"
  #   target: "_.local" # optional html tag target attribute

  - name: ""
    icon: "fa fa-code-fork"
    items:
      - name: "Immich"
        logo: "https://user-images.githubusercontent.com/27055614/182044984-2ee6d1ed-c4a7-4331-8a4b-64fcde77fe1f.png"
        subtitle: "Immich - pictures"
        tag: "app"
        url: "http://immich.beefunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "LingoDiaryImmich"
        logo: "http://lingodiary.beefunk.local/static/icon_reduced.png"
        subtitle: "LingoDiary - language learning"
        tag: "app"
        url: "http://lingodiary.beefunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "Music"
        logo: "assets/navidrome.png"
        subtitle: "Navidrome - music streaming"
        tag: "app"
        url: "http://navidrome.beefunk.local"
        target: "_.local" # optional html tag target attribute

      # - name: "Music - RompR"
      #   logo: "https://fatg3erman.github.io/RompR/images/favicon-128.png"
      #   subtitle: "rompR MPD client- music"
      #   tag: "app"
      #   url: "http://beefunk:8089"
      #   target: "_.local" # optional html tag target attribute

      - name: "Music - myMPD"
        logo: "https://avatars.githubusercontent.com/u/765844?v=4"
        subtitle: "myMPD MPD client- music"
        tag: "app"
        url: "http://mympd.beefunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "Music - Moode"
        logo: "https://moodeaudio.org/forum/images/moode-r900-logotype-175px.png"
        subtitle: "MPD Moode Server"
        tag: "app"
        url: "http://moode.local"
        target: "_.local" # optional html tag target attribute

      - name: "Movies"
        logo: "assets/jellyfin.png"
        subtitle: "Jellyfin - media streaming"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        target: "_.local" # optional html tag target attribute
        url: "http://jellyfin.beefunk.local"

      #      - name: "Tubesync"
      #logo: "http://beefunk:1021/images/tubesync.png"
      #subtitle: "Tubesync - youtube video/channel downloader"
      #tag: "app"
      ## Optional tagstyle
      #tagstyle: "is-success"
      #target: "_.local" # optional html tag target attribute
      #url: "http://beefunk:4848"

      #      - name: "Remote Control"
      #logo: "assets/openelec.png"
      #subtitle: "Openelec/Kodi - remote control"
      #tag: "app"
      ## Optional tagstyle
      #tagstyle: "is-success"
      #url: "http://10.1.1.102:8080"
      #        target: "_.local" # optional html tag target attribute       target: "_.local" # optional html tag target attribute

      - name: "Comics"
        logo: "assets/komga.png"
        subtitle: "Komga - Comics streaming"
        tag: "app"
        tagstyle: "is-success"
        url: "http://komga.beefunk.local"
        target: "_.local"

      - name: "Ebooks"
        logo: "assets/calibre.png"
        subtitle: "Calibre Web - Ebooks download"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "http://calibre-web.beefunk.local"
        target: "_.local"

      - name: "Audiobooks"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/audiobookshelf.png"
        subtitle: "AudiobookShelf - Audiobook streaming"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "http://audiobookshelf.beefunk.local"
        target: "_.local"

      - name: "File Browser"
        logo: "http://filebrowser.beefunk.local/static/img/logo.svg"
        subtitle: "Filebrowser - explore and download files on server"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "http://filebrowser.beefunk.local"
        target: "_.local"

  - name: ""
    icon: ""
    items:
      - name: "Pictures"
        logo: "assets/lens.png"
        subtitle: "Piwigo - Picture gallery"
        tag: "loz"
        url: "http://piwigo.beefunk.local"
        target: "_.local" # optional html tag target attribute

      # - name: "Tablet Slideshow"
      #   logo: "assets/lens.png"
      #   subtitle: "Tablet Slideshow"
      #   tag: "loz"
      #   url: "http://beefunk:5671/piwigo-random.html"
      #   target: "_.local" # optional html tag target attribute
      #
      - name: "Photoprism"
        logo: "assets/photoprism.png"
        subtitle: "Photoprism - Picture gallery"
        tag: "loz"
        url: "http://beefunk:2342"
        target: "_.local" # optional html tag target attribute

      - name: "Blog - El Camino Loco"
        logo: "assets/wordpress.png"
        subtitle: "Wordpress - El Camino Loco"
        tag: "loz"
        url: "http://beefunk:5555"
        target: "_.local" # optional html tag target attribute

      - name: "Music Sheet"
        logo: "assets/solfege.png"
        subtitle: "A list of sheet played throughtout years"
        tag: "cloud"
        url: "http://brownfunk.local:3000/s/BW3Tx522S#"
        target: "_.local" # optional html tag target attribute

  - name: "Cloud"
    icon: ""
    items:
      - name: "Cloud storage"
        logo: "assets/nextcloud.png"
        subtitle: "Nextcloud - cloud storage"
        tag: "cloud"
        url: "https://brownfunk.local:9393"
        target: "_.local" # optional html tag target attribute

      - name: "Syncthing"
        logo: "https://beefunk:8384/assets/img/logo-horizontal.svg"
        subtitle: "Sync data between devices"
        tag: "cloud"
        url: "https://beefunk:8384"
        target: "_.local" # optional html tag target attribute
      #
      #
      # - name: "Notes"
      #   logo: "assets/clipboard.png"
      #   subtitle: "CodiMD - Note taking in Markdown"
      #   tag: "cloud"
      #   url: "http://beefunk:3000"
      #   target: "_.local" # optional html tag target attribute
      #
      # - name: "Wallabag"
      #   logo: "assets/wallabag.png"
      #   subtitle: "Wallabag - Pin and save web pages - read them later"
      #   tag: "cloud"
      #   url: "http://beefunk:3637"
      #   target: "_.local" # optional html tag target attribute
      #
  - name: "Download"
    icon: "fa fa-code-fork"
    items:
      - name: "Torrent"
        logo: "assets/transmission.png"
        subtitle: "Transmission + VPN - torrent download"
        tag: "dl"
        url: "http://transmission.beefunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "Jackett"
        logo: "assets/jackett.png"
        subtitle: "Jackett - torrent proxy"
        tag: "dl"
        url: "http://jackett.beefunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "Prowlarr"
        logo: "http://prowlarr.beefunk.local/Content/Images/logo.png"
        subtitle: "Prowlarr - Search torrent"
        tag: "dl"
        url: "http://prowlarr.beefunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "Music Download"
        logo: "assets/lidarr.svg"
        subtitle: "Lidarr - music download"
        tag: "dl"
        url: "http://lidarr.brownfunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "Movie Download"
        logo: "assets/radarr.png"
        subtitle: "Radarr - movie download"
        tag: "dl"
        url: "http://radarr.beefunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "Movie (French) Download"
        logo: "assets/radarr.png"
        subtitle: "Radarr - french movie download"
        tag: "dl"
        url: "http://brownfunk.local:7879"
        target: "_.local" # optional html tag target attribute

      - name: "TV show Download"
        logo: "assets/sonarr.png"
        subtitle: "Sonarr - movie download"
        tag: "dl"
        url: "http://sonarr.beefunk.local"
        target: "_.local" # optional html tag target attribute

      - name: "Subtitle Download"
        logo: "assets/bazarr.png"
        subtitle: "Bazarr - subtitle download"
        tag: "dl"
        url: "http://brownfunk.local:6768"
        target: "_.local" # optional html tag target attribute

      - name: "Downloader"
        logo: "assets/pyload.png"
        subtitle: "Pyload - download any link to server"
        tag: "dl"
        url: "http://brownfunk.local:8000"
        target: "_.local" # optional html tag target attribute

      - name: "Firefox"
        logo: "assets/firefox.png"
        subtitle: "Firefox"
        tag: "dl"
        url: "https://beefunk:3009"
        target: "_.local" # optional html tag target attribute

  - name: "Server Maintenance"
    icon: "fa fa-code-fork"
    items:
      - name: "Pi Hole"
        logo: "assets/pihole.png"
        subtitle: "Pi Hole - adblocker DNS & DHCP server"
        tag: "geek"
        url: "http://pihole.beefunk.local/admin"
        target: "_.local" # optional html tag target attribute

      - name: "Router"
        logo: "assets/asusrouter.png"
        subtitle: "Router config"
        tag: "geek"
        url: "http://192.168.1.1"
        target: "_.local" # optional html tag target attribute

      #      - name: "OpenMediaVault"
      #logo: "assets/omv.png"
      #subtitle: "OpenMediaVault - Admin"
      #tag: "geek"
      #url: "http://beefunk:85"
      #        target: "_.local" # optional html tag target attribute

      # - name: ".localces"
      #   logo: "assets/.localces.png"
      #   subtitle: ".localces - realtime"
      #   tag: "geek"
      #   url: "http://beefunk:61208"
      #   target: "_.local" # optional html tag target attribute
      #
      # - name: "Netdata"
      #   logo: "assets/netdata.png"
      #   subtitle: "Monitor - realtime"
      #   tag: "geek"
      #   url: "http://beefunk:19999"
      #   target: "_.local" # optional html tag target attribute
      #
      - name: "Scrunity"
        logo: "https://raw.githubusercontent.com/AnalogJ/scrutiny/master/webapp/frontend/src/assets/images/logo/scrutiny-logo-dark.png"
        subtitle: "Monitor HDD - realtime"
        tag: "geek"
        url: "http://beefunk:8033"
        target: "_.local" # optional html tag target attribute

      - name: "Cockpit"
        logo: "assets/cockpit.png"
        subtitle: "Debian console - VM"
        tag: "geek"
        url: "https://beefunk.local:9090"
        target: "_.local" # optional html tag target attribute

      - name: "Grafana"
        logo: "assets/grafana.png"
        subtitle: "Grafana monitoring - admin(secret)"
        tag: "geek"
        url: "http://beefunk:3005"
        target: "_.local" # optional html tag target attribute

      # - name: "PhpMyAdmin"
      #   logo: "assets/phpmyadmin.png"
      #   subtitle: "PhpMyAdmin"
      #   tag: "geek"
      #   url: "http://beefunk:3002"
      #   target: "_.local" # optional html tag target attribute
      #
      - name: "Ebooks"
        logo: "assets/calibre.png"
        subtitle: "Calibre Server - Ebooks Maintenance"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "http://beefunk:8081"
        target: "_.local"

      - name: "Ownfoil"
        logo: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/nintendo-switch.svg"
        subtitle: "Ownfoil - switch games"
        tag: "app"
        # Optional tagstyle
        tagstyle: "is-success"
        url: "http://ownfoil.beefunk.local"
        target: "_.local"

      - name: "Portainer"
        logo: "assets/portainer.png"
        subtitle: "Portainer - docker images"
        url: "http://portainer.beefunk.local"
        tag: "geek"
        target: "_.local" # optional html tag target attribute

