version: "3.9"

services:
  mpd-dynamic:
    build: .
    container_name: mpd-dynamic
    restart: unless-stopped
    environment:
      - TZ=Australia/Sydney
    # Mount the NAS config into the container's home directory
    volumes:
      - ./config:/root/.config
    networks:
      - default
